'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CompVMInstaller.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property animations() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("animations", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property compviewmodelbannersmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("compviewmodelbannersmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property demo_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("demo_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property demo_grenadelauncher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("demo_grenadelauncher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property demo_grenadelauncher_inspect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("demo_grenadelauncher_inspect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property demo_melee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("demo_melee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property demo_stickybomb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("demo_stickybomb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property demo_stickybomb_inspect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("demo_stickybomb_inspect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property engineer_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("engineer_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property engineer_gunslinger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("engineer_gunslinger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property engineer_pda_build() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("engineer_pda_build", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property engineer_pda_destruct() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("engineer_pda_destruct", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property engineer_pistol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("engineer_pistol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property engineer_pistol_inspect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("engineer_pistol_inspect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property engineer_pomson() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("engineer_pomson", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property engineer_shotgun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("engineer_shotgun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property engineer_shotgun_inspect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("engineer_shotgun_inspect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property engineer_toolbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("engineer_toolbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property engineer_wrangler() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("engineer_wrangler", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property engineer_wrench() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("engineer_wrench", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property engineer_wrench_inspect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("engineer_wrench_inspect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property heavy_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heavy_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property heavy_fists() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heavy_fists", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property heavy_minigun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heavy_minigun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property heavy_minigun_inspect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heavy_minigun_inspect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property heavy_sandvich() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heavy_sandvich", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property heavy_shotgun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heavy_shotgun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property heavy_shotgun_inspect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heavy_shotgun_inspect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property medic_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medic_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property medic_medigun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medic_medigun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property medic_medigun_inspect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medic_medigun_inspect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property medic_melee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medic_melee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property medic_syringegun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medic_syringegun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property preload_room() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("preload_room", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property pyro_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pyro_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property pyro_flamethrower() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pyro_flamethrower", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property pyro_flamethrower_inspect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pyro_flamethrower_inspect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property pyro_flaregun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pyro_flaregun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property pyro_melee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pyro_melee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property pyro_shotgun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pyro_shotgun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property pyro_shotgun_inspect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pyro_shotgun_inspect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property scout_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scout_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property scout_drink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scout_drink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property scout_fan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scout_fan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property scout_melee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scout_melee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property scout_milk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scout_milk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property scout_pistol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scout_pistol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property scout_pistol_inspect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scout_pistol_inspect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property scout_push() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scout_push", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property scout_scattergun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scout_scattergun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property scout_scattergun_inspect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scout_scattergun_inspect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property scout_shortstop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scout_shortstop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property sniper_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sniper_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property sniper_huntsman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sniper_huntsman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property sniper_jarate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sniper_jarate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property sniper_melee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sniper_melee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property sniper_smg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sniper_smg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property sniper_smg_inspect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sniper_smg_inspect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property sniper_sniperrifle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sniper_sniperrifle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property sniper_sniperrifle_inspect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sniper_sniperrifle_inspect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property soldier_banner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("soldier_banner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property soldier_bison() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("soldier_bison", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property soldier_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("soldier_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property soldier_melee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("soldier_melee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property soldier_original() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("soldier_original", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property soldier_rocketlauncher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("soldier_rocketlauncher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property soldier_rocketlauncher_inspect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("soldier_rocketlauncher_inspect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property soldier_shotgun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("soldier_shotgun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property soldier_shotgun_inspect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("soldier_shotgun_inspect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property spy_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spy_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property spy_deadringer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spy_deadringer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property spy_disguisekit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spy_disguisekit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property spy_inviswatch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spy_inviswatch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property spy_knife() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spy_knife", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property spy_knife_inspect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spy_knife_inspect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property spy_revolver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spy_revolver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property spy_revolver_inspect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spy_revolver_inspect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property spy_sapper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spy_sapper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
